--创建银行卡签约信息表
DROP TABLE SIGN_BANK_CARD;
CREATE TABLE SIGN_BANK_CARD(
ID						VARCHAR(20)			NOT NULL PRIMARY KEY,
CARD_NO		VARCHAR(64)			NOT NULL,
CARD_TYPE				CHAR(1) 	DEFAULT 'D' NOT NULL ,
INST_ID			VARCHAR(16)			NOT NULL ,
INST_NAME					VARCHAR(32)			NOT NULL,
inst_country_code			VARCHAR(16)				DEFAULT '',
inst_district_code			VARCHAR(16)		DEFAULT '',
inst_province	 VARCHAR(16)	DEFAULT '',
inst_city			VARCHAR(16)			DEFAULT '',
inst_branch	 VARCHAR(16)		DEFAULT '',
user_name	VARCHAR(64)	NOT NULL,
certificate_type	VARCHAR(8)	NOT NULL,
certificate_no	VARCHAR(40)	NOT NULL,
Mobile_phone	VARCHAR(11)	default '',
Tel_phone	Varchar(20)	default '',
gmt_create	timestamp(6)	NOT NULL,
gmt_modified	timestamp(6)	NOT NULL

);

CREATE UNIQUE INDEX SIGN_BANK_CARD_UNQ_IDX1 ON SIGN_BANK_CARD(CARD_NO);
COMMENT ON COLUMN SIGN_BANK_CARD.ID IS '序号';
COMMENT ON COLUMN SIGN_BANK_CARD.CARD_NO IS '卡号, 如果是信用卡卡号是存储CCDC提供的索引卡号';
COMMENT ON COLUMN SIGN_BANK_CARD.CARD_TYPE IS '卡类型,C：贷记卡，D：借记卡，S:准贷记卡';
COMMENT ON COLUMN SIGN_BANK_CARD.INST_ID IS '机构编号,和金融主数据保持一致';
COMMENT ON COLUMN SIGN_BANK_CARD.INST_NAME IS '机构名称，和金融主数据保持一致';
COMMENT ON COLUMN SIGN_BANK_CARD.inst_country_code IS '机构所在国家代码，和金融主数据保持一致';
COMMENT ON COLUMN SIGN_BANK_CARD.inst_district_code IS '机构所在地区代码';
COMMENT ON COLUMN SIGN_BANK_CARD.inst_province IS '机构所在省份';
COMMENT ON COLUMN SIGN_BANK_CARD.inst_city IS '机构所在城市';
COMMENT ON COLUMN SIGN_BANK_CARD.inst_branch IS '机构分支';
COMMENT ON COLUMN SIGN_BANK_CARD.user_name IS '用户姓名';
COMMENT ON COLUMN SIGN_BANK_CARD.certificate_type IS '证件类型';
COMMENT ON COLUMN SIGN_BANK_CARD.certificate_no IS '证件号码';
COMMENT ON COLUMN SIGN_BANK_CARD.Mobile_phone IS '手机号';
COMMENT ON COLUMN SIGN_BANK_CARD.Tel_phone IS '电话';
COMMENT ON COLUMN SIGN_BANK_CARD.gmt_create IS '生成时间';
COMMENT ON COLUMN SIGN_BANK_CARD.gmt_modified IS '最近一次修改时间';

--创建用户签约银行卡相关信息表
DROP TABLE SIGN_USER_CARD_RELATION;
CREATE TABLE SIGN_USER_CARD_RELATION(
ID						VARCHAR(20)			NOT NULL PRIMARY KEY,
Sign_id			VARCHAR(32)	NOT NULL,
User_id			VARCHAR(32)	NOT NULL,
sign_bank_card_id	VARCHAR(20)	NOT NULL,
agreement_no	VARCHAR(32)	default '',
bank_id	VARCHAR(16)	NOT NULL,
sign_channel_id varchar(16) not null,
sign_type		CHAR(16)	NOT NULL,
sign_product_type	varchar(32)	not null default 'F2P',
Alias	VARCHAR(50)	,
IsMaster	CHAR(1)	,
Status	CHAR(1)	NOT NULL,
memo	varchar(128)	,
gmt_active	timestamp(6)	NOT NULL,
gmt_cancel	timestamp(6)	DEFAULT NULL,
gmt_create	timestamp(6)	NOT NULL,
gmt_modified	timestamp(6)	NOT NULL
);

CREATE UNIQUE INDEX SIGN_RELATION_UNQ_IDX1 ON SIGN_USER_CARD_RELATION(Sign_id,bank_id);

COMMENT ON COLUMN SIGN_USER_CARD_RELATION.ID IS '序号';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.Sign_id IS '签约ID, 会有重复';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.User_id IS '用户ID';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.sign_bank_card_id IS '签约卡表的id';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.agreement_no IS '协议编号，如果有';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.bank_id IS '签约银行';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.Sign_channel_id IS '签约渠道代码，和主数据里一致';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.sign_type IS '签约类型';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.Alias IS '协议别名';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.IsMaster IS '是否是主签约, Y/N';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.Status IS '状态,N:正常，C:关闭';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.gmt_active IS '激活时间';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.gmt_cancel IS '取消时间';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.gmt_create IS '生成时间';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.gmt_modified IS '最近一次修改时间';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.sign_product_type IS '签约产品类型';
COMMENT ON COLUMN SIGN_USER_CARD_RELATION.memo IS '备注';

--sequence
CREATE SEQUENCE SIGN_BANK_CARD_ID_SEQ INCREMENT BY 1 START WITH 1  MINVALUE 1 MAXVALUE 999999999999 CYCLE  nocache;
CREATE SEQUENCE SIGN_USER_CARD_RELATION_ID_SEQ INCREMENT BY 1 START WITH 1  MINVALUE 1 MAXVALUE 999999999999 CYCLE  nocache;
